import type { MediaTag } from "../schema";

/**
 * Photos of Kot Pot 1 from its public Google Maps listing
 * (https://maps.google.com/?cid=10087072950070230599), downloaded on 2026-09-25.
 * `storefront-sign` was posted by the restaurant itself; every other photo was
 * posted by a guest, who is credited in the caption. Menu boards, price and hours
 * signs, videos and close-ups of people were left out. Files live in
 * /public/images/google, resized to 2000px and stripped of metadata; three were
 * cropped to drop a printed menu corner or a passing hand.
 */
export type SeedPhoto = {
  file: string;
  alt: string;
  caption?: string;
  tag: MediaTag;
  width: number;
  height: number;
  featured?: boolean;
  focalX?: number;
  focalY?: number;
  sourceUrl: string;
};

const credit = (what: string, who: string) => `${what}. Photo: ${who} via Google Maps`;
const photo = (id: string) => `https://lh3.googleusercontent.com/gps-cs-s/${id}=s0`;

/** In gallery order. `storefront-sign` is featured so the Visit section shows it. */
export const GOOGLE_PHOTOS: SeedPhoto[] = [
  { file: "google/galbi-steak-grill.jpg", alt: "Two marinated short ribs and a raw steak on the tabletop grill", caption: credit("Short ribs and steak on the grill", "Vanesa Huang"), tag: "bbq", width: 2000, height: 1333, sourceUrl: photo("AHRPTWl61A8v-uyRCK_Du9Ksjy2ZR23Hl6fCbMo-UFiBGMJHkq5qt5EAzBSVvJsoq2o1ztmOIYzD3F2tAO4EcdCoTQHzq_tBSIQQOlD2AoH9BplDMktHHk2cu2F0RvnDFp_ljoOfLm2zuJr0Zc8w") },
  { file: "google/hot-pot-crab.jpg", alt: "Hot pot simmering with crab legs, corn, fish cake and bok choy", caption: credit("Crab legs, corn and bok choy in the pot", "Laura Almaraz"), tag: "hot-pot", width: 1500, height: 2000, sourceUrl: photo("AHRPTWnhZ44XwDQJ2IY5QSaINoGhHobMJdUU7gg__KrL7wCk60lcGsbxuTyiwjf-jaihz6jVM-i6N-NP4bYAOqX3Gox5aY_5whsAp4mkSNGd-jKQeVVlB0MVDu1XkPnCTbTSh3JrKKTDfQ4nYVKo") },
  { file: "google/neon-logo-wall.jpg", alt: "Red neon Kot Pot Korean BBQ & Hot Pot logo on a black marble wall", caption: credit("The neon logo wall", "Andrew Bazan"), tag: "interior", width: 1500, height: 2000, sourceUrl: photo("AHRPTWn3bcB1xAzPW9ZnDOK9LzolURpHUkFQ7EZU2CtK3_Yw1dcBbRZ2m5Qiiei0ivJqVIgh-L8PH5Yj7LrAQusbATRPZed8C43NWlLmbnJU0I-WSnY006NTMIYFm_wzmouUP05Ajb1dyCSoZfvK") },
  { file: "google/steak-shrimp-galbi-tray.jpg", alt: "Tray of raw steaks, shrimp and marinated short ribs", caption: credit("Steak, shrimp and short ribs ready for the grill", "Vanesa Huang"), tag: "bbq", width: 2000, height: 1333, sourceUrl: photo("AHRPTWliMN6uBZcfAN1wSwnl7V3NHQyr63RRC2ew5t-sOk7aLS0F81KDLr8kvuoMbxHXwqp1QQryZjNQ-w3lLSC7bAKJsM69RXDyh0l_C1EylBz71SbJFP9S7UgIqLkpmU9r_MZONR36qysJ2dc") },
  { file: "google/hot-pot-creamy-broth.jpg", alt: "Creamy hot pot broth with enoki mushrooms, bok choy and a red date", caption: credit("Creamy broth with enoki and a red date", "Andrea Barnes"), tag: "hot-pot", width: 2000, height: 2000, sourceUrl: photo("AHRPTWk8Y94iUfLJsFDrPun4xpA1TS7KmSURrvHpwmuRlaLLowDEuy-dBRUK7zcSt0_bh-ZThA44bW_nQ7cGLmwc-oih2U6z3awhnj-Zeu64VywFBpWinN9xwQ5P12P9h4g14P3I7RDPsGqXfEMm") },
  { file: "google/entrance-night.jpg", alt: "Red neon Kot Pot sign over the front entrance at night", caption: credit("The front entrance at night", "Saul Sandoval"), tag: "exterior", width: 1500, height: 2000, focalY: 35, sourceUrl: photo("AHRPTWlMmaWHtiHNaWtYmPugNTv7dMpoyW5eZ3rNYSBkzd_2fApaeup11FZYpjJBPRL-6eRNTOyv44wMWZWbsMD615H3WkEXnOMgFEz504pDDYQvPpXqVBOLGmMG1RiZFSh45G8mo2f5MQ86m8Y") },
  { file: "google/kimchi-zucchini.jpg", alt: "Kimchi, grilled zucchini and pickled radish on a Kot Pot plate", caption: credit("Kimchi, zucchini and pickled radish", "Eldon Lopez"), tag: "banchan", width: 1560, height: 2000, sourceUrl: photo("AHRPTWk06G4xNGzxrhDoZ8QsCd-diH1UkwB_80oNWPiCKw4sB4H92SPqStS8jxu5rLeoDE1Z3T77cYw1l-gWy1OURgg4EZCiA6tMg8eXba6uwwod4L5v4p6SzB1dyerbLMfrv3y9iRvLLMrnPklO") },
  { file: "google/raw-meats-seafood.jpg", alt: "Marinated meats, vegetables, noodles, shrimp, clams, fish balls and crab legs laid out beside the burner", caption: credit("Meats and seafood laid out by the burner", "Joan Y"), tag: "hot-pot", width: 1500, height: 2000, sourceUrl: photo("AHRPTWm2ie0n7AGQEMNP8rm3J20NlsXkudtWnhdzMZf7TpkVOqxlcFUaG_NVYe3977JJ8Vx9_XSf25eoyrmAhKsoIRhA2BXX8PDiW9ew70PNinguawShO34YSJzTN5RzR0BIk1nx4cKT_tskjl6x") },
  { file: "google/grilled-steaks.jpg", alt: "Steak and short ribs searing on the tabletop grill", caption: credit("Steak and short ribs searing", "Vanesa Huang"), tag: "bbq", width: 2000, height: 1333, sourceUrl: photo("AHRPTWkWfTsmvDcb58WvT8ZxNefBCk4lRCtV4Uv0w1Jp8dDJlPsgrp10J8nHU6ht7j5WwgM9T7ME7drKpba0kiCoOncBPcLclNnXQhB92Nlbq3PqYWrqmI16fhxsOBijjr_aMfRXqrdyotJ4s50") },
  { file: "google/moon-gate-fountain.jpg", alt: "Moon-gate water feature with bonsai trees and a small deer figure", caption: credit("The moon-gate fountain", "Eldon Lopez"), tag: "interior", width: 1600, height: 1393, sourceUrl: photo("AHRPTWn-LPNPmz9Izw4xoQm_DdW2PGM_eeMJ4t5ZUNt9dZ4Sa6US-E0myeUU9iLB6w52MKfsvqvVdpfxs6o_k7cwHw7CpUlbQV5AZ51vigDClLQBO0sxTwcRWFEpt_qUzf9PPmbu4ImYJlPgwWZF") },
  { file: "google/table-spread.jpg", alt: "A full table from above: meats, vegetables, two broths, sauces and drinks", caption: credit("A full table from above", "Olguita Olivares"), tag: "other", width: 1920, height: 1080, sourceUrl: photo("AHRPTWmK0F6yoVp7ug85ySZD8BHPrtFFYmFmBkSfJ84PuaT7uTvyqvDnrlczco-QIpTG6yBnqJ0L6Mu8rlCxV6kIbr4BG_1xPHtfj_6U5sVuj6YcCGK5SW4QsX2i4VX1iAHf45vGPn5gx1FbE1t_") },
  { file: "google/marinated-meats-tray.jpg", alt: "Tray of short ribs, sliced beef, spicy pork and marinated beef", caption: credit("Short ribs, sliced beef and marinated meats", "Laura Almaraz"), tag: "bbq", width: 2000, height: 1095, sourceUrl: photo("AHRPTWmhNhPnLX0okoU0qwPq11GDnTL9FNQ8qyxZcfRroCHQT845L8KlEkhjqte5UDVHhTGWKhoGN0yAiBXBNlVDss6VPZUPpId4nrbtZVWOceLQFu8i5FVTShe5s4C-1Eg1iYcgto_YMOa7m0tK") },
  { file: "google/hot-pot-sliced-beef.jpg", alt: "Hot pot broth heating on the burner beside a plate of thinly sliced beef", caption: credit("Broth on the burner and sliced beef", "Andrea Barnes"), tag: "hot-pot", width: 2000, height: 2000, sourceUrl: photo("AHRPTWkB84CF19ITHy13cZ8FN_WF6stV5Rpv4j_Sn7U8zhp-MeuLXlgwHwTz3W_LGLIXfAloqgba2hNklJ5nYYgAZ3uuV8ecDVDxC4IpFRf3IV_5D9k894jrVjyotml1pWinCKvS_dhVkaG5eQZB") },
  { file: "google/storefront-sign.jpg", alt: "Kot Pot Korean BBQ & Hot Pot sign lit over the storefront at dusk", caption: credit("The storefront at dusk", "Kot Pot 1"), tag: "exterior", width: 2000, height: 1500, featured: true, focalY: 40, sourceUrl: photo("AHRPTWmm9WUh6ZcPJFMHlmW0mcBcaSU-NBNk4jEvQMrgjjrIN17qeewR6JvEGc7OYVA2Apyq53qPA08sa6CxZzVPzOXc2YnJDEupruR1sxIkKWDcK-5AWjXLPdvCnLAsru308xSgOxE7wGzvrAPT") },
  { file: "google/mixed-grill.jpg", alt: "Steak, chicken, shrimp and zucchini on the grill", caption: credit("Steak, chicken, shrimp and zucchini", "Eldon Lopez"), tag: "bbq", width: 1600, height: 1600, sourceUrl: photo("AHRPTWnYe2SgWV4Y7C08qavvsmTtfUuFBGWRJus0goCk17_lkz_gk4j6Hx2ZtkdS15q3qFWXSmZXWfp3gIKTVOB6cHhxnqIe3686TKVeV4YS2gXQAiU6FIeTXFUhpfVBa4JJ_sNkfT5vr7dD6jeY") },
  { file: "google/vegetable-tray.jpg", alt: "Tray of zucchini, corn, onion, broccoli and udon noodles", caption: credit("Vegetables and udon for the pot", "Laura Almaraz"), tag: "hot-pot", width: 2000, height: 1500, sourceUrl: photo("AHRPTWmaW7FFJCg2pl4GiZPJa3GVgrbjq13dbZG1OaWlautob1zS0Zp7Dq1e11vwD5l-bt0piE17lQKJGMU1vFtrnT66nddKq9hPL0B_m0hVU_IlnRt7fVW4cZF6uUamCOxQAdr6br-ov2xcBPzt") },
  { file: "google/crab-legs.jpg", alt: "Platter of cracked snow crab legs", caption: credit("Snow crab legs", "Park Jae Hyung"), tag: "hot-pot", width: 1500, height: 2000, sourceUrl: photo("AHRPTWnNZEXu0gF-vVkcy0f96bM-Pe_21GcFPM1Dg7Lal_HXXEcyJL1su5ItQnuZxyDqyUPB17lwKoPYak2Qk58EzvkLIaIbaas4p_V3LnMXFN0WyeqRuZ7sLSDmmso0i3mG0yzk6wUmfauB_QCm") },
  { file: "google/dining-room.jpg", alt: "Dining room with a marble feature wall, grill tables and window seating", caption: credit("The dining room", "Alma Garza"), tag: "interior", width: 1500, height: 2000, sourceUrl: photo("AHRPTWnVxv4EVbWCTweAI2K3Ei7zW9TyNTuzR4s2dBzwKHYlAqzjRmJSAHO1wKkyAvpmyEP-GltuKk1cjXdLVLc2EQjHmLohgWrk6j6iLhLUriDTUKgj-nPFmlUP1ulqJOW98ivO1VtjpnkEV2w4") },
  { file: "google/bulgogi-shrimp-grill.jpg", alt: "Bulgogi and shrimp cooking on the grill", caption: credit("Bulgogi and shrimp on the grill", "Alex Ackerman"), tag: "bbq", width: 1500, height: 2000, sourceUrl: photo("AHRPTWkJtHXFr_zLA-JcnhX_o10wg0EBgD7VeqAdQ9Og71ZPiGGG8xPJIyScSoZ0_FyNB3oiLoWsEGLxcMyvUF_dXwZjo6gNkobHsuCz-f7ie07fTlzkLo23b4-KNKlNZlwr-LNYsNXuqEg8DHA") },
  { file: "google/hot-pot-add-ins.jpg", alt: "Tray of fish balls, meatballs, sausages, imitation crab, shrimp and luncheon meat", caption: credit("Fish balls, sausages and shrimp for the pot", "Andrew Bazan"), tag: "hot-pot", width: 1500, height: 1740, sourceUrl: photo("AHRPTWl5vkN07W0G9AI1bNV3YfEGm_aRVu_lu077ybjfa7LaL_ameQerRw_LsKKnuNt2MNPG0Rf97RqU8COfosA0ZzEPLYc_pCwPOfZGeG5j6954-S5vlK1C0dnqwpCdGHqF_lv9gy0RkgFzJnZM") },
  { file: "google/steak-cuts.jpg", alt: "Three raw steaks on a tray beside the grill", caption: credit("Three cuts for the grill", "Saul Sandoval"), tag: "bbq", width: 2000, height: 1500, sourceUrl: photo("AHRPTWmsrLean3Nt3VOVbJV5EveiWSz2yIWCEedyQO9MMHS5bJvsSiYMTkGeN_rim9JradyDB40_bW-Rl_8bPJFvCbehKanSUNPZtIuxbUZxEnCJbW336oXf3NzxHBW_vaOtFKSOE18tVWYoDPk") },
  { file: "google/drink-cup.jpg", alt: "Yellow drink in a tall Kot Pot branded cup", caption: credit("A drink in a Kot Pot cup", "Maya Hernandez"), tag: "drinks", width: 1500, height: 2000, sourceUrl: photo("AHRPTWmiEyvjpHb3NDpoJXu82Uu509-YGPv-_eL7UC-Dd5huUTudXIlDhkZlq4Jyw3Uk8WdgohOSEX2iickZalGjO4u2fC8mqzDbO6NpsYHvIFDg3dpwWfgLd6KZqmxz5ctwEu_nPwR__XqnHJU") },
  { file: "google/salmon-grill.jpg", alt: "Salmon and marinated meat on the grill", caption: credit("Salmon and marinated meat on the grill", "Luis Alberto Luna Zacatenco"), tag: "bbq", width: 2000, height: 1500, sourceUrl: photo("AHRPTWk72AjQn6Sgbs7-9EFVvOy3zDSs7s0tl6eR_RBiHj3wzPmGQIiIRuzm4KCye2dHSn-8Y1pKre4SJRI_VEEOo_o451cgq6-6gf1dnLm2DH4GDYukB2o3QlAGQZCUaSOSng3uqcrbiGFfRpWP") },
  { file: "google/hot-pot-table.jpg", alt: "Hot pot with seafood beside plates of pork belly, sliced beef, greens and dipping sauces", caption: credit("Hot pot with pork belly and sliced beef", "Vero Rocha"), tag: "hot-pot", width: 2000, height: 1500, sourceUrl: photo("AHRPTWn7i5MMw-bwmwz9g4oZ-gd0FqwIsGAuzXqBg-Ydbp-Mp6xPlmlFdQ5D0Y332S4ORIKywt4zMEP_WW9GAAQuCBuOW5LK5k2AbbQNf-4gr7YacoSOD4wQZuKMpYE5ZBfvWeHwiH7_2ToBzTU") },
  { file: "google/lobby-fountain.jpg", alt: "Lobby water feature with the Kot Pot logo projected on the floor", caption: credit("The lobby fountain", "Andrew Bazan"), tag: "interior", width: 1500, height: 2000, sourceUrl: photo("AHRPTWl83cQ3Lq_2zIVCpGKKVmV8vRvtS3NtZGhqNFdq6UOJQi58GNnSBq7fiXDONqX6NqehccMy4IPDX0PhKCWDp07cLjr9et8OLSeymO32FuY4zF3696Rc-aZvbOQHhn-9LlgLIgQfVHKutRF_") },
  { file: "google/sliced-meat-rolls.jpg", alt: "Rolls of thinly sliced meat on a plate", caption: credit("Thinly sliced meat, rolled", "L (momlifenomlife)"), tag: "hot-pot", width: 1500, height: 2000, sourceUrl: photo("AHRPTWmFYTl6kBcEGvEgQiT7c76z5lOduwlKuSc3GBAw4wC3MTEVCBZfOMcRG4ihD96B0oey02-PuioaSVUL0TBGZwM7epS_28P2rV-fP31MFf7viMeSC3dNWWs1TrsRsq96OvQM0shbiBEtfu1X") },
  { file: "google/dessert.jpg", alt: "A cup of ice cream and a slice of layered cake", caption: credit("Ice cream and cake", "Luis Alberto Luna Zacatenco"), tag: "other", width: 2000, height: 1500, sourceUrl: photo("AHRPTWkgu3URCz9dsAsHLsEUbgHsqM87FInqN4k_AaZaMiQqN4WDQs8hRX1Plufd4DC9ManYi7wBvDwby3MH_8nI8YxCSVQZTWtdvWquYdKhQA-qxTeam2C_toZlXET6b-iqGt8kpLdz0SWPUSE") },
  { file: "google/parking-lot-night.jpg", alt: "The restaurant lit up at night, seen from the parking lot", caption: credit("The restaurant from the parking lot at night", "Reuben Reyes"), tag: "exterior", width: 2000, height: 1500, focalY: 45, sourceUrl: photo("AHRPTWlB7d2lMRByLF_CYn7kDr9d1CZA_sMxW8f9afka-duzhxAJuW9QcCOwKCL3hxkCylRj83qfm75iaL41Az-CEsaadWcX2zofCBo2cG18QmlrHq8DPgjrcvLKkXKLOpuWttUB8RjNO7ffs2kV") },
  { file: "google/storefront-day.jpg", alt: "Storefront, patio railing and stone lion in daylight", caption: credit("The storefront by day", "Kassy Rodriguez"), tag: "exterior", width: 2000, height: 1126, sourceUrl: photo("AHRPTWkSTmj99Gz1oKYS4hEJirI-cvrcpafLllnSMl_rdUWan7t4tYZ1Z-hY_FyWXGNs7vah_uPj6U-6rGyeMYazT8ZaUGmM9i8cvm7QZt0o4HfVaDMrJhLaohC_gQfmkNCKnd0StVh0wAb3Bpg") },
  { file: "google/induction-burner.jpg", alt: "Kot Pot branded induction burner set into a table", caption: credit("The tabletop induction burner", "Andrew Bazan"), tag: "interior", width: 1500, height: 2000, sourceUrl: photo("AHRPTWkt7DEjxTqRq_d-9t_BUY-Ec2h2aGG2FQgKa2KGbJGgSTpqu2AVB3ijxS-kcKhNMQGR55QtwXaNZKKiQa7-dNQpRgxaLEDI15mWzWhJNOv9hU2nMenzxzVYQ7A2zibrGrd107yOQlj8R752") },
];
